package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseItem<M extends BaseItem<M>> extends Model<M> implements IBean {

	public void setItemID(String itemID) {
		set("itemID", itemID);
	}

	public String getItemID() {
		return get("itemID");
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setPic(String pic) {
		set("pic", pic);
	}

	public String getPic() {
		return get("pic");
	}

	public void setPrice(Double price) {
		set("price", price);
	}

	public Double getPrice() {
		return get("price");
	}

	public void setExpressPrice(Double expressPrice) {
		set("expressPrice", expressPrice);
	}

	public Double getExpressPrice() {
		return get("expressPrice");
	}

	public void setSale(Integer sale) {
		set("sale", sale);
	}

	public Integer getSale() {
		return get("sale");
	}

	public void setOrigin(String origin) {
		set("origin", origin);
	}

	public String getOrigin() {
		return get("origin");
	}

	public void setBrand(String brand) {
		set("brand", brand);
	}

	public String getBrand() {
		return get("brand");
	}

	public void setYear(String year) {
		set("year", year);
	}

	public String getYear() {
		return get("year");
	}

	public void setMeterial(String meterial) {
		set("meterial", meterial);
	}

	public String getMeterial() {
		return get("meterial");
	}

	public void setCommonID(String commonID) {
		set("commonID", commonID);
	}

	public String getCommonID() {
		return get("commonID");
	}

	public void setDetailID(String detailID) {
		set("detailID", detailID);
	}

	public String getDetailID() {
		return get("detailID");
	}

}
