package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDetail<M extends BaseDetail<M>> extends Model<M> implements IBean {

	public void setDetailID(String detailID) {
		set("detailID", detailID);
	}

	public String getDetailID() {
		return get("detailID");
	}

	public void setItemID(String itemID) {
		set("itemID", itemID);
	}

	public String getItemID() {
		return get("itemID");
	}

	public void setDescribleText(String describleText) {
		set("describleText", describleText);
	}

	public String getDescribleText() {
		return get("describleText");
	}

	public void setDescribleImg(String describleImg) {
		set("describleImg", describleImg);
	}

	public String getDescribleImg() {
		return get("describleImg");
	}

}
