package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserID(String userID) {
		set("userID", userID);
	}

	public String getUserID() {
		return get("userID");
	}

	public void setName(String name) {
		set("name", name);
	}

	public String getName() {
		return get("name");
	}

	public void setPassword(String password) {
		set("password", password);
	}

	public String getPassword() {
		return get("password");
	}

	public void setProfileImage(String profileImage) {
		set("profileImage", profileImage);
	}

	public String getProfileImage() {
		return get("profileImage");
	}

	public void setAddressID(Integer addressID) {
		set("addressID", addressID);
	}

	public Integer getAddressID() {
		return get("addressID");
	}

}
