package common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setOrderID(String orderID) {
		set("orderID", orderID);
	}

	public String getOrderID() {
		return get("orderID");
	}

	public void setUserID(String userID) {
		set("userID", userID);
	}

	public String getUserID() {
		return get("userID");
	}

	public void setItemDetailID(String itemDetailID) {
		set("itemDetailID", itemDetailID);
	}

	public String getItemDetailID() {
		return get("itemDetailID");
	}

}
