package common.model;

import com.demo.common.model.base.BaseCommon;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Common extends BaseCommon<Common> {
	public static final Common dao = new Common();
}
