package common.model;

import com.demo.common.model.base.BaseDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Detail extends BaseDetail<Detail> {
	public static final Detail dao = new Detail();
}
