package common.model;

import java.util.Map;

import com.demo.common.model.base.BaseItem;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Item extends BaseItem<Item> {
	public static final Item dao = new Item();
	public Page<Item> paginate(int pageNumber, int pageSize) {
		Page<Item> p = paginate(pageNumber, pageSize, "select *", "from item");
		for(int i = 0; i < p.getList().size(); i++){
			if(null == p.getList().get(i).getPic()){
				p.getList().get(i).setPic("无");
			}
		}
		return p;
	}
	
	@Override
	public Map<String, Object> getAttrs() {
		// TODO Auto-generated method stub
		return super.getAttrs();
	}
}
