package common.model;

import com.demo.common.model.base.BaseItemdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Itemdetail extends BaseItemdetail<Itemdetail> {
	public static final Itemdetail dao = new Itemdetail();
}
