package common.model;

import java.util.List;

import com.demo.common.model.base.BaseOrder;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Order extends BaseOrder<Order> {
	public Page<Order> paginate(int pageNumber, int pageSize) {
		Page<Order> p = null;
		p = paginate(pageNumber, pageSize, "select *", " from `order`");
		return p;
	}
	
	public List<Order> getOrderIDByUserID(String userId){
		List<Order> l = Db.query("select * from `order` where userID = " + userId);
		return l;
	}
	public static final Order dao = new Order();
}
