package common.model;

import java.util.Map;

import com.demo.common.model.base.BaseUser;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */
	public Page<User> paginate(int pageNumber, int pageSize) {
		Page<User> p = paginate(pageNumber, pageSize, "select *", "from user");
		for(int i = 0; i < p.getList().size(); i++){
			if(null == p.getList().get(i).getProfileImage()){
				p.getList().get(i).setProfileImage("无");
			}
		}
		return p;
	}
	@Override
	public Map<String, Object> getAttrs() {
		// TODO Auto-generated method stub
		return super.getAttrs();
	}
}
